language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 7.0
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=34

matrix:
  finish_fast: true
  include:
    - php: 5.6
      env: COMPOSER_CMD=install

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install: if [ "$COMPOSER_CMD" = "install" ]; then composer install --prefer-dist; else composer update --prefer-dist; fi

before_script:
  - app/console doctrine:phpcr:init:dbal --force -e=test
  - app/console doctrine:phpcr:repository:init -e=test

script: phpunit -c app

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
